name: debian

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_without_convert:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run script
        run: |
          ./vista-fonts-installer.sh --accept-microsoft-eula

      - name: Test if directory is created with desired fonts
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-debian-raw.txt" "result.txt"

  build_with_convert:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run script
        env:
          CONVERT_TTF: true
          MS_FONT_PATH: fonts
          ACCEPT_EULA: true
        run: |
          ./vista-fonts-installer.sh

      - name: Test if directory is created with desired fonts
        env:
          MS_FONT_PATH: fonts
        run: |
          ./tests/test_directory.sh "tests/expected-files-debian-converted.txt" "result.txt"

  build_and_except_eula_manually:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run script
        run: |
          yes "yes" | ./vista-fonts-installer.sh

      - name: Test if directory is created with desired fonts
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-debian-raw.txt" "result.txt"

  build_and_reject_eula_manually:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run script
        run: |
          yes "no" | ./vista-fonts-installer.sh

      - name: Test if directory is created with desired fonts
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-debian-raw.txt" "result.txt" "check_present"
