name: linux-mint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_without_convert:
    runs-on: ubuntu-latest
    container: vcatechnology/linux-mint
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-mint-raw.txt" "accept_eula_by_parameter"

  build_with_convert:
    runs-on: ubuntu-latest
    container: vcatechnology/linux-mint
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          CONVERT_TTF: true
          MS_FONT_PATH: fonts
          ACCEPT_EULA: true
        run: |
          ./tests/test_directory.sh "tests/expected-files-mint-converted.txt"

  build_and_except_eula_manually:
    runs-on: ubuntu-latest
    container: vcatechnology/linux-mint
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-mint-raw.txt" "accept_eula_manually"

  build_and_reject_eula_manually:
    runs-on: ubuntu-latest
    container: vcatechnology/linux-mint
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisite packages
        run: |
          apt-get update
          apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-mint-raw.txt" "reject_eula"
