name: macos

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_without_convert:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install brew packages
        run: |
          brew install cabextract
          brew install fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: ~/Library/Fonts/Microsoft
        run: |
          ./tests/test_directory.sh "tests/expected-files-macos-raw.txt" "accept_eula_by_parameter"

  build_with_convert:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install brew packages
        run: |
          brew install cabextract
          brew install fontforge

      - name: Run test script
        env:
          CONVERT_TTF: true
          ACCEPT_EULA: true
          MS_FONT_PATH: ~/Library/Fonts/MS
        run: |
          ./tests/test_directory.sh "tests/expected-files-macos-converted.txt"

  build_and_except_eula_manually:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install brew packages
        run: |
          brew install cabextract
          brew install fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: ~/Library/Fonts/Microsoft
        run: |
          ./tests/test_directory.sh "tests/expected-files-macos-raw.txt" "accept_eula_manually"

  build_and_reject_eula_manually:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install brew packages
        run: |
          brew install cabextract
          brew install fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: ~/Library/Fonts/Microsoft
        run: |
          ./tests/test_directory.sh "tests/expected-files-macos-raw.txt" "reject_eula"
