name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_without_convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-ubuntu-raw.txt" "accept_eula_by_parameter"

  build_with_convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          CONVERT_TTF: true
          MS_FONT_PATH: fonts
          ACCEPT_EULA: true
        run: |
          ./tests/test_directory.sh "tests/expected-files-ubuntu-converted.txt"

  build_and_except_eula_manually:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl cabextract fontforge

      - name: Run test script
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-ubuntu-raw.txt" "accept_eula_manually"

  build_and_reject_eula_manually:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install prerequisite packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl cabextract fontforge

      - name: Test if directory is created with desired fonts
        env:
          MS_FONT_PATH: /usr/share/fonts/truetype/vista
        run: |
          ./tests/test_directory.sh "tests/expected-files-ubuntu-raw.txt" "reject_eula"
